### ISSUE TITLE
Design quarto website

### ISSUE THREAD

**Issue by telepath37** [pharmaverse/falcon#35]
The website should contain:

- [x] **Landing Page/Homepage**: general information, need to be visually appealing, properly linked with subpages
- [x] **Getting Started**: how to load packages, how to navigate to the specific output/template, how to run examples (with dummy data and instructions on how to link it with real data, etc.)
- [x] **Template Library**: each entry has the FDA guidance template screenshot, as well as the code & output examples
- [x] **Our Journey of Collaboration**: from both business and developer perspectives, could also contain talks/presentations
- [x] **FAQ**

Refer to https://quarto.org/docs/gallery/ and https://nbdev.fast.ai/ to get ideas on the design and please comment below to share any ideas/thoughts (Be Creative!!!). The website could contain more and less pages than suggested above, the list just serves as a starting point for brainstorming.

**Linked issues:**
- [x] #45 
- [x] #44 
- [x] #40
- [x] #36 
- [x] #37
- [x] #38
- [x] #39

**Comment by jknizia** [comment]
First mock idea
![image](https://user-images.githubusercontent.com/85986258/234792423-b065579e-885c-452f-a1b4-3d38917e02ea.png)

**Comment by aassuied-ps** [comment]
First mock idea for general layout. I made a sidebar like NEST. I really have troubles using the `auto:` statement in the yaml.

![image](https://user-images.githubusercontent.com/123543888/234826085-f05566d7-7d68-42b2-8d35-2b11d896d84b.png)
